In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#data variablecsv valus is stored
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent = dataset[['charges']]

In [8]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [10]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 0.30, random_state = 0)

In [11]:
X_train

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]

In [12]:
y_train

          charges
1163   2200.83085
196    5649.71500
438   12592.53450
183    7419.47790
1298   5261.46945
...           ...
763    3070.80870
835    7160.33030
1216   5415.66120
559    1646.42970
684    4766.02200

[936 rows x 1 columns]

In [13]:
X_test

      age     bmi  children  sex_male  smoker_yes
578    52  30.200         1         1           0
610    47  29.370         1         0           0
569    48  40.565         2         1           1
1034   61  38.380         0         1           0
198    51  18.050         0         0           0
...   ...     ...       ...       ...         ...
1261   28  37.100         1         1           0
494    21  25.700         4         1           1
97     55  38.280         0         1           0
418    64  39.160         1         1           0
920    62  25.000         0         0           0

[402 rows x 5 columns]

In [14]:
y_test

          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [186]:
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor (n_estimators=1000 ,criterion="poisson", random_state=0)
regressor=regressor.fit(X_train,y_train)

C:\Anaconda\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [193]:
y_pred = regressor.predict(X_test)
y_pred

array([11622.38904332, 10423.78976802, 44898.57184872, 13043.1826513 ,
        9518.56202408, 12580.28738026,  1969.1007707 , 11472.31339622,
        7311.42115618,  5583.74468248,  7476.9292391 , 18973.14885558,
       10447.21909912,  6409.99246345, 24112.55025637, 13974.05387793,
       13574.749079  ,  3560.52504937,  6465.96276096, 33925.24904901,
       23869.8930941 , 14901.06911897, 10886.7829757 , 27386.81598133,
        2760.63691948,  5394.63762168,  4984.62810718,  8078.72776835,
        3713.4411362 ,  9413.8246775 ,  7947.55395791, 48422.45871495,
       13947.0454855 , 12985.34642971, 17229.09089542,  3909.55226329,
        8858.00142116, 37897.59671753, 39523.15091504,  3202.36350311,
        9665.38553828,  4273.56317743, 20809.616945  , 47703.40321605,
       37476.24350221,  3799.43629525, 14147.2217787 ,  6587.218427  ,
        4914.07439612, 12838.47864678,  3970.44344897,  4594.29270069,
       26486.64923654, 48354.88345456, 11799.8053693 , 10013.05443191,
        4295.21440399, 10875.12562332,  9517.2803654 , 16603.87350961,
        1720.11519787, 46946.17425549, 16349.49973583, 18729.180768  ,
       12380.06297539,  9867.35296913, 33790.47108747, 40693.09447254,
        3316.46044425, 12395.96184263, 18686.9707945 , 12370.98437439,
       16944.0905684 , 14131.73091789, 13527.89944871, 15537.79420706,
        8255.72535548, 14425.1384743 , 19736.79550617, 46621.88522462,
       11549.9170015 , 49995.69075369,  3918.93427448, 10083.6003796 ,
       40951.16392853, 19210.33626697,  3961.98820068,  3253.73369628,
       14215.49678479, 39701.85007431,  5655.47857494, 14051.4722434 ,
        2968.13427082,  9881.712944  ,  9785.60045346,  4226.56492656,
       43224.25219816, 53357.56476021,  5438.30321935, 10996.35586389,
        3042.38809244,  8431.86415671,  7573.80584621, 40444.3856358 ,
       27790.66272455,  4201.54828333, 11346.06422171,  7020.9660635 ,
       11594.68694617, 45337.70677422, 12173.8321518 ,  6868.34703005,
       10208.74513505, 34426.03369918, 48006.06458408,  7147.03955142,
        2390.48776692, 10993.00488307, 22109.60380757,  9329.38292096,
       41833.78372113, 12881.92057349, 14573.53337925,  8420.13738765,
       10595.63206799,  5288.97413346, 26933.76029498, 26596.25083557,
       48432.81935182,  1754.20896658, 17189.15572733,  3953.58870299,
        6267.69016224,  9003.82661187, 42996.05529927, 38037.32061991,
       25232.48960209, 16783.0017248 , 24248.68098297,  7345.86693005,
        2014.35420807, 12465.96187601, 10314.20248875, 11091.47365234,
        7061.44223806, 14291.50765736, 22637.19350158, 13950.55168697,
        1569.5083007 , 12333.45043453,  6217.30137088, 39129.54498376,
        9960.07248002,  9682.98661309,  3330.95726505,  8202.24840899,
        3727.12841729,  6751.28744183, 13991.82797573, 10801.48495113,
        7246.8883296 , 13233.83853965, 13832.21710348,  9223.98146475,
        4245.79152906, 10072.94285625, 17260.88991586,  6586.72036712,
        4521.24721057,  2164.78630614,  7377.56889292,  6732.37917966,
       12578.29908533,  2676.38723547, 11834.40170609,  9935.18945087,
        4785.02715516,  7065.78276023, 26879.33238589,  1684.88110304,
       17722.50427535,  6783.83163989, 11451.70602012,  8193.66956967,
        9258.91886193, 28075.68009707,  3392.74744874,  3152.09452419,
       14180.9791137 , 11209.63587927, 41424.97904737,  6768.37716927,
        5452.5832115 , 24821.48230165,  3240.26933538,  2908.73088215,
        9326.58198505,  6395.11798165,  9440.73188013,  4377.13756467,
       12348.5443558 , 46826.90140908, 17330.40214586, 18911.16748775,
       10746.3185352 , 43508.02785646,  4647.15813531, 10020.47894753,
        7282.93794258,  1835.4691522 ,  9171.06813193, 13679.52354105,
        6762.93430754,  4653.67847918,  6555.66866676, 10532.33805513,
        6885.33435436,  6863.82645137, 14219.12182409,  6922.06556052,
       13430.18980945,  7922.86883504, 12195.7907309 ,  7975.50201687,
       13868.94333333, 14315.0191732 , 22095.58028261, 12202.75576966,
        7258.49309244,  2799.31100756, 11041.01092122,  8209.52336049,
       15285.68169613,  4263.42657251,  5310.89898831,  7223.25922026,
       14339.00995545, 34453.65213792,  5892.295499  , 12756.60317895,
        6041.82824443, 37163.39285429,  8190.52461915,  7257.23314061,
       12601.64806103, 10581.16572414,  3275.90859038,  8398.86091223,
        3026.47651525,  6713.05126512, 19661.0861042 , 46400.32614452,
        5332.88666844,  3809.38779709,  5982.44114381,  1595.46303799,
        8392.99528017,  3120.29611265,  7346.25527724,  9469.54726694,
        8844.75584117, 25090.76877965, 45946.27974862, 16730.29666627,
        6525.21393145, 11170.81843675, 44798.33461458, 10063.02155707,
       39597.44741889,  1854.34548752, 38530.80548958,  5345.27725325,
       12907.20956378,  6375.59669754, 40372.22149828,  6440.89747571,
        9939.47063293, 10905.19676446,  4064.33863733, 16867.89732038,
       12191.53489635, 10781.14816652, 13528.38988251, 14719.5999644 ,
        7977.82994759,  5313.31296614, 10065.25007805, 22206.4673711 ,
        4012.44392254,  1686.97884114,  2536.75907937, 46843.69598036,
       11806.63524291,  4584.1126866 , 15074.12173631, 13986.88715567,
       34576.33072878,  6864.97382688,  5449.49804742,  9194.600309  ,
        3276.6212233 ,  4409.48436462, 21193.179597  , 16730.94896363,
       13640.1988148 ,  2826.81485362,  3396.60940946, 13187.68410595,
       10232.2665175 , 15395.60979896, 20145.19954674,  9622.33363356,
       16791.64093061,  2440.78879971, 13189.90584697,  9778.43998966,
       16709.94158425,  2587.44127689,  7122.6516695 , 46564.94570171,
        3780.85720946,  5848.74417308,  1832.64195494, 13337.22517693,
        6701.9334279 , 12010.51694841, 46805.97429301, 17767.2782083 ,
        9153.36191184, 44498.9615313 , 15897.54145475, 10756.81481117,
       10687.85276066,  5339.9290045 , 28313.72002245,  4756.69776542,
       14495.62555412,  2365.23192191, 16479.40072817,  3405.9118571 ,
       24460.94916825, 11938.81592928,  7965.81144062, 40610.33560459,
        6698.81319115,  5250.4877183 , 29360.67795881,  3254.15967594,
       10197.36499949,  3868.88520418, 11579.13730381,  3790.40946796,
        7788.70259632,  6575.45184398, 46541.51097319,  9999.42960793,
       45948.20165676, 38906.25652595,  5908.16052455, 11748.34747861,
        1707.31851594,  4809.58593471,  3159.26360573,  9680.50166111,
       46134.47975112, 11520.45914055,  1911.60392495, 13730.02015677,
        2204.62801441, 12490.59967822,  8077.11027647,  2370.54066664,
        3554.55354421, 36872.29291033,  6729.66616917,  2013.20451375,
       41079.35967267, 12742.75593958, 42878.42560447, 11767.80066718,
        7555.20959744,  3273.1655807 ,  2120.10256725, 17136.16724772,
        5299.235585  ,  1968.1798151 , 12107.02679144,  7204.74881099,
        6145.70037322,  6666.79153144,  8776.61067524, 43958.72602232,
        3842.78802039, 12369.82283655,  7239.27017305, 19551.74511273,
       10997.94948659,  6338.78303704, 17088.91032045, 12953.01694953,
       19846.82937745, 18987.03487142])

In [194]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [195]:
r_score

0.8548927583265962

In [204]:
import pickle
filename="finalized_model_Forest.sav"
pickle.dump(regressor,open(filename,'wb'))

In [212]:
loaded_model=pickle.load(open("finalized_model_Forest.sav",'rb'))
result=loaded_model.predict([[30,21,2,1,0]])

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [213]:
result

array([5181.28826637])